name: Build MeldMC-Installer

on:
  pull_request:
    branches: [master, main]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Conan
        run: pip install conan

      - name: Detect Conan profile
        run: conan profile detect --force

      - name: Cache Conan packages
        uses: actions/cache@v4
        with:
          path: ~/.conan2/p
          key: conan-${{ runner.os }}-${{ hashFiles('conanfile.*') }}
          restore-keys: |
            conan-${{ runner.os }}-

      - name: Install dependencies
        run: conan install . --build=missing -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True

      - name: Configure CMake
        run: cmake -S . -DCMAKE_TOOLCHAIN_FILE=build/Release/generators/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: make -j

      - name: Strip binary
        run: strip --strip-unneeded MeldInstaller

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MeldInstaller-linux-x64
          path: MeldInstaller
