name: Build MeldMC-Installer

on:
  pull_request:
    branches: [ master, main ]
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  build-java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build Java version
        run: |
          cd java
          mvn clean package

      - name: Upload Java artifact
        uses: actions/upload-artifact@v4
        with:
          name: meldmc-installer-java
          path: java/target/meldmc-installer.jar

  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libgl1-mesa-dev xorg-dev

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: go-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-${{ runner.os }}-

      - name: Download dependencies
        run: go mod download

      - name: Build (static)
        run: CGO_ENABLED=1 go build -ldflags="-s -w -extldflags=-static" -a -installsuffix cgo -o meldmc-installer .

      - name: Strip binary
        run: strip meldmc-installer

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: meldmc-installer-linux-x64
          path: meldmc-installer

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~\go\pkg\mod
          key: go-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-${{ runner.os }}-

      - name: Download dependencies
        run: go mod download

      - name: Build (static)
        run: go build -ldflags="-s -w -H windowsgui" -o meldmc-installer.exe .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: meldmc-installer-windows-x64
          path: meldmc-installer.exe

  build-mac-x64:
    runs-on: macos-13
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: go-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-${{ runner.os }}-

      - name: Download dependencies
        run: go mod download

      - name: Build (static)
        run: CGO_ENABLED=1 go build -ldflags="-s -w" -o meldmc-installer .

      - name: Strip binary
        run: strip meldmc-installer

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: meldmc-installer-mac-x64
          path: meldmc-installer

  build-mac-aarch64:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: go-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-${{ runner.os }}-

      - name: Download dependencies
        run: go mod download

      - name: Build (static)
        run: CGO_ENABLED=1 go build -ldflags="-s -w" -o meldmc-installer .

      - name: Strip binary
        run: strip meldmc-installer

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: meldmc-installer-mac-aarch64
          path: meldmc-installer
